version: '3.8'
services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/python:3.12"
    volumes:
      - ../..:/workspaces:cached      
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: workshop

# volumes:
#   postgres-data: